<%
// This is just a placeholder for the SQL migration file
// The actual SQL was generated by: npx prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script
// and applied directly via psql
%>